title: AsciiDoc Evangelist
# Раскомментируйте /blog если хотите разместить сайт в подпапке, например http://example.com/blog
#baseurl: /blog
description: Проект Jekyll AsciiDoc Quickstart - это помощь в создании собственного сайта, размещенного на GitHub, с контентом на основе AsciiDoc.
exclude:
- LICENSE
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay
  # Build settings
markdown: kramdown