= AsciiDoc Evangelist

Проект AsciiDoc Evangelist основнам на шаблоне AsciiDoc-сайта для Jekyll link:https://github.com/asciidoctor/jekyll-asciidoc-quickstart/blob/main/README.adoc[Jekyll AsciiDoc Quickstart] за авторством link:https://github.com/mojavelinux[Dan Allen] предоставляет быстрый способ создания сайта на основе AsciiDoc с использованием инфраструктуры публикации GitHub.
Этот проект сочетает в себе возможности AsciiDoc с элегантной основой CSS и шаблоном для блога.
Поскольку это шаблон репозитория, все, что вам нужно сделать, это создать новый репозиторий из этого репозитория, чтобы создать свой сайт. 

[IMPORTANT]
Живой сайт, созданный на основе этого репозитория, можно найти по адресу https://koshlensky.github.io/ascii-evangelist/.

Проект предоставляет рабочий процесс GitHub Actions, который публикует сайт каждый раз, когда в репозиторий вносятся изменения.
Рабочий процесс следит за коммитами в ветке *main* (или *master*), автоматически запускает сборку Jekyll с включенным плагином AsciiDoc и размещает сгенерированное содержимое в ветке *gh-pages*, откуда оно и размещается.

Проект распространяется по лицензии MIT. Русифицированный файл лицензии прилагается.
Copyright (C) 2015 - настоящее время Джон Эриксен и проект Asciidoctor
