= Стайлгайд по работе с AsciiDoc
:showtitle:
:page-navtitle: Стайлгайд по работе с AsciiDoc
:page-excerpt: Excerpt goes here.
:page-root: ../../../

*AsciiDoc* — это формат текстового документа для написания заметок, документации, статей, книг, электронных книг, слайд-шоу, веб-страниц, страниц руководства и блогов. Файлы AsciiDoc можно перевести во многие форматы, включая HTML, PDF, EPUB, справочную страницу.

В статье рассмотрены:

. xref:2024-05-05-first-entry.adoc#General_requirements[Общие требования к работе в Asciidoc]
. xref:2024-05-05-first-entry.adoc#Best_practices[Лучшие практики]
. xref:2024-05-05-first-entry.adoc#Headings1[Заголовки]
. xref:2024-05-05-first-entry.adoc#Images[Изображения]
. xref:2024-05-05-first-entry.adoc#Lists[Списки]
. xref:2024-05-05-first-entry.adoc#References[Ссылки]
. xref:2024-05-05-first-entry.adoc#Formulas[Формулы]
. xref:2024-05-05-first-entry.adoc#Admonitions[Примечания]
. xref:2024-05-05-first-entry.adoc#Code[Код]
. xref:2024-05-05-first-entry.adoc#Anchors[Якоря]
. xref:2024-05-05-first-entry.adoc#Tables[Таблицы]
. xref:2024-05-05-first-entry.adoc#Main_colors[Управление цветом]

[#General_requirements]
== Общие требования к работе в Asciidoc

[#Best_practices]
== Лучшие практики

[#Headings1]
== Заголовки

Заголовки должны идти последовательно — не ставьте заголовки третьего уровня без заголовков второго.

`=` — заголовок первого уровня (один на весь adoc-файл), ставится в начале страницы;

`==` — заголовок второго уровня;

`===` — заголовок третьего уровня.

Заголовок второго уровня автоматически создает разделитель. Если вам нужно убрать его — добавьте перед заголовком атрибут `[discrete]`:

[source]
----
[disсrete]
== Заголовок второго уровня
----

[#Images]
== Изображения

Картинки чувствительны к регистру и указанному формату — будьте внимательны и отслеживайте ошибки в вашей среде разработки. Обычно в них встроен механизм, который помогает достраивать ссылки, в том числе и на изображения.

Управляйте масштабом ваших изображений через `[width=%]`. Например, 20%:

image:https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPmyXEJ45xyKurNNufIRT0E1uo4KPov-Vp0ECoLLWNSw&s[width=20%]

Управляйте расположением изображений, сославшись через `image{two-colons} (с двумя двоеточиями для принудительного переноса)` и используя атрибуты `center` (центрировать), `left` (левый край), `right` (правый край). Например, по центру:

image::https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPmyXEJ45xyKurNNufIRT0E1uo4KPov-Vp0ECoLLWNSw&s[align="center", width=50%]

[#Lists]
== Списки

Нумерованные списки задаются точками `.`:


. Первый номер списка, первый уровень вложенности
. Второй номер списка, первый уровень вложенности

. Первый уровень списка, первый уровень вложенности
.. Второй уровень списка, второй уровень вложенности
... Третий уровень списка, третий уровень вложенности

Маркированные списки задаются звездочками `*`:

* На первом уровне вложенности
* На первом уровне вложенности

* Первый уровень вложенности
** Второй уровень вложенности
*** Третий уровень вложенности

Чтобы соединить списки с блоком контента используйте `+`:

* Первый уровень
+
Абзац на том же уровне, что и список первого уровня
+
image:https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPmyXEJ45xyKurNNufIRT0E1uo4KPov-Vp0ECoLLWNSw&s[width=20%]

** Второй уровень
+
Абзац на том же уровне, что и список второго уровня

Аналогично для маркированного списка.

////
== Block Underlines

* Comment Block `////`

* Passthrough Block `++++`

* Listing Block `----`

* Literal Block `....`

* Sidebar Block ****

* Quote Block ____

* Example Block ====

* Open Block --
////

[#References]
== Ссылки

Для внутренних ссылок на файлы (xref) и на изображения (image) используется относительный путь. Для ссылок из сети интернет (link) используется URL.

В квадратных скобках [] в конце внутренних и внешних ссылок можно задать текст, отображаемой вместо текста (alt-text) по умолчанию (имя заголовка adoc-файла или сама ссылка).

[#Formulas]
== Формулы

При составлении формул пользуйтесь сайтом   link:https://asciimath.org/[].

Используйте бэкслэши \, чтобы избавиться от зарезервированных слов. Например, stem:[le] создает знак ≤, используйте \ "l\e" если хотите получить неизмененный результат. Список зарезервированных слов смотрите link:https://asciimath.org/[здесь].

Для создания пробелов в формулах используйте пробел в кавычках " " или бэкслэш \ (обратная косая черта).

Вы можете создавать формулы как через stem:[], так и через конструкцию:

[stem]
++++
++++

[#Admonitions]
== Примечания

Примечания (admonitions) задаются заглавными буквами в квадратных скобках. Идущий после примечания абзац будет автоматически выбран как содержимое примечания. Если в примечание необходимо добавить несколько абзацев — оберните содержимое в четыре знака равенства `====`:

[NOTE]
Содержимое примечания в один абзац.

[NOTE]
====
Содержимое примечания первого абзаца.

Содержимое примечания второго абзаца.
====

Доступны следующие примечания:

[NOTE]
Текст Note (примечание).

[TIP]
Текст Tip (совет).

[IMPORTANT]
Текст Important (важно).

[CAUTION]
Текст Caution (внимание).

[WARNING]
Текст Warning (предупреждение).

[#Code]
== Код

Укажите код используя конструкцию:

----
код
----

Дополнительно можете указать язык обработки блока кода — блок будет отображать синтаксис аналогично заданному языку. Например, python:

[source, python]
----
name = input('What is your name?')
print('Hey! your name is' + name)
----

[#Anchors]
== Якоря

Якорь ссылается на конкретное место adoc-файла и задается в квадратных скобках с использованием решетки `#`. Например, [#anchor_1]. Учитываются правила:

* Якорь не могут иметь одинаковых названий в одном adoc-файле.

* Якорь может быть выставлен в любом месте adoc-файла с нового абзаца.

* Якорь не будет работать внутри форматируемых блоков по типу stem:[] или блоков кода, имеющих собственный синтаксис:
+
[source]
----
[#якорь]
== Название раздела на который хотим сослаться
----

Чтобы сослаться на якорь, добавьте его идентификатор в конце ссылки xref, но до квадратных скобок []. Например:

[source]
----
xref:адок-файл_1#anchor_1[] #сослались на якорь [#anchor_1] в файле адок-файл_1.adoc.
----

[#Tables]
== Таблицы

Границы таблицы задаются с помощью `|===`, а для составления ячеек используются `|`. Перед таблицей можно использовать квадратные скобки `[]` для задания настроек:

[]
|===
|ячейка 1 |ячейка 2
|ячейка 3 |ячейка 4
|===

Можно не использовать квадратные скобки `[]`, тогда таблица построится по умолчанию:

|===
|ячейка 1 |ячейка 2
|ячейка 3 |ячейка 4
|===

Выделение заголовка полужирным может задаваться как через `[%header]`, так и через `[options="header"]`:

[%header]
|===
|ячейка 1 |ячейка 2
|ячейка 3 |ячейка 4
|===

[options="header"]
|===
|ячейка 1 |ячейка 2
|ячейка 3 |ячейка 4
|===

[#Main_colors]
== Управление цветом

Изменение цвета текста осуществляется через встроенные роли `[.color]`, где `color` — желаемый цвет, например `[.aqua]` создаст [.aqua]#Аквамариновый цвет#. Доступны следующие цвета для стандартных ролей:

[cols=",a", grid=none, frame=none, width=70%]
|===
>|*[.aqua]* |[.aqua]
Аквамариновый
>|*[.black]* |[.black]
Черный
>|*[.blue]* |[.blue]
Синий
>|*[.fuchsia]* |[.fuchsia]
Фуксия
>|*[.gray]* |[.gray]
Серый
>|*[.green]* |[.green]
Зеленый
>|*[.lime]* |[.lime]
Лайм
>|*[.maroon]* |[.maroon]
Темно-бордовый
>|*[.navy]* |[.navy]
Темно-синий
>|*[.olive]* |[.olive]
Оливковый
>|*[.purple]* |[.purple]
Фиолетовый
>|*[.red]* |[.red]
Красный
>|*[.silver]* |[.silver]
Серебряный
>|*[.teal]* |[.teal]
Сине-зеленый
>|*[.white]* |[.white]
Белый
>|*[.yellow]* |[.yellow]
Желтый
|===

== Вспомогательные ресурсы AsciiDoctor Docs

. link:https://docs.asciidoctor.org/asciidoc/latest/macros/images/[Изображения]
. link:https://docs.asciidoctor.org/asciidoc/latest/lists/unordered/[Списки]
. link:https://docs.asciidoctor.org/asciidoc/latest/macros/links/[Ссылки]
. link:https://docs.asciidoctor.org/asciidoc/latest/stem/[Формулы]
. link:https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/[Примечания]
. link:https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/[Код]
. link:https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/[Якоря]
. link:https://docs.asciidoctor.org/asciidoc/latest/tables/build-a-basic-table/[Таблицы]